# # Use postgres/example user/password credentials
# version: '3.9'

# services:

#   db:
#     image: postgres
#     restart: always

#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}

#     ports:
#       - "5432:5432"

services:
  db:
    image: postgres:16.4
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
